# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'seans_ekleme.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_seans_saat_label(object):
    def setupUi(self, seans_saat_label):
        seans_saat_label.setObjectName("seans_saat_label")
        seans_saat_label.resize(504, 377)
        seans_saat_label.setStyleSheet("background-color:black;")
        self.seans_adi_label = QtWidgets.QLabel(seans_saat_label)
        self.seans_adi_label.setGeometry(QtCore.QRect(90, 110, 101, 16))
        self.seans_adi_label.setStyleSheet("color:white;\n"
"font-size:20px;\n"
"")
        self.seans_adi_label.setObjectName("seans_adi_label")
        self.seans_ekle_buton = QtWidgets.QPushButton(seans_saat_label)
        self.seans_ekle_buton.setGeometry(QtCore.QRect(30, 240, 421, 33))
        self.seans_ekle_buton.setStyleSheet("background-color:white; \n"
"color:red;\n"
"font-size:15px;font-style:italic;font-weight:bold;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/images/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.seans_ekle_buton.setIcon(icon)
        self.seans_ekle_buton.setIconSize(QtCore.QSize(25, 25))
        self.seans_ekle_buton.setObjectName("seans_ekle_buton")
        self.seans_ekleme_paneli = QtWidgets.QLabel(seans_saat_label)
        self.seans_ekleme_paneli.setGeometry(QtCore.QRect(90, 50, 331, 31))
        self.seans_ekleme_paneli.setStyleSheet("padding-left:35px;\n"
"font-weight:bold;\n"
"font-size:21px;\n"
"color:white;\n"
"")
        self.seans_ekleme_paneli.setObjectName("seans_ekleme_paneli")
        self.ana_menu_button = QtWidgets.QPushButton(seans_saat_label)
        self.ana_menu_button.setGeometry(QtCore.QRect(30, 290, 207, 33))
        self.ana_menu_button.setStyleSheet("background-color:white;font-size:15px;color:red;font-weight:bold;font-style:italic;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/images/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ana_menu_button.setIcon(icon1)
        self.ana_menu_button.setIconSize(QtCore.QSize(25, 25))
        self.ana_menu_button.setObjectName("ana_menu_button")
        self.cikisButton = QtWidgets.QPushButton(seans_saat_label)
        self.cikisButton.setGeometry(QtCore.QRect(250, 290, 206, 33))
        self.cikisButton.setStyleSheet("background-color:white;font-size:15px;color:red;font-weight:bold;font-style:italic;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/images/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cikisButton.setIcon(icon2)
        self.cikisButton.setIconSize(QtCore.QSize(25, 25))
        self.cikisButton.setObjectName("cikisButton")
        self.seans_adi_edit = QtWidgets.QLineEdit(seans_saat_label)
        self.seans_adi_edit.setGeometry(QtCore.QRect(210, 110, 161, 21))
        self.seans_adi_edit.setObjectName("seans_adi_edit")
        self.seans_tarih_edit = QtWidgets.QDateTimeEdit(seans_saat_label)
        self.seans_tarih_edit.setGeometry(QtCore.QRect(210, 150, 151, 21))
        self.seans_tarih_edit.setStyleSheet("background-color:white;")
        self.seans_tarih_edit.setDate(QtCore.QDate(2022, 5, 6))
        self.seans_tarih_edit.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.seans_tarih_edit.setObjectName("seans_tarih_edit")
        self.seans_tarih_label = QtWidgets.QLabel(seans_saat_label)
        self.seans_tarih_label.setGeometry(QtCore.QRect(90, 150, 101, 16))
        self.seans_tarih_label.setStyleSheet("color:white;\n"
"font-size:20px;\n"
"")
        self.seans_tarih_label.setObjectName("seans_tarih_label")
        self.seans_tarih_label_2 = QtWidgets.QLabel(seans_saat_label)
        self.seans_tarih_label_2.setGeometry(QtCore.QRect(90, 190, 101, 16))
        self.seans_tarih_label_2.setStyleSheet("color:white;\n"
"font-size:20px;\n"
"")
        self.seans_tarih_label_2.setObjectName("seans_tarih_label_2")
        self.seans_saat_edit = QtWidgets.QTimeEdit(seans_saat_label)
        self.seans_saat_edit.setGeometry(QtCore.QRect(210, 190, 151, 22))
        self.seans_saat_edit.setStyleSheet("background-color:white;")
        self.seans_saat_edit.setObjectName("seans_saat_edit")

        self.retranslateUi(seans_saat_label)
        QtCore.QMetaObject.connectSlotsByName(seans_saat_label)

    def retranslateUi(self, seans_saat_label):
        _translate = QtCore.QCoreApplication.translate
        seans_saat_label.setWindowTitle(_translate("seans_saat_label", "Seans Ekle"))
        self.seans_adi_label.setText(_translate("seans_saat_label", "Seans Adı:"))
        self.seans_ekle_buton.setText(_translate("seans_saat_label", "Seans Ekle"))
        self.seans_ekleme_paneli.setText(_translate("seans_saat_label", "Seans Ekleme Paneli"))
        self.ana_menu_button.setText(_translate("seans_saat_label", "Ana Menü"))
        self.cikisButton.setText(_translate("seans_saat_label", "Çıkış"))
        self.seans_tarih_edit.setDisplayFormat(_translate("seans_saat_label", "d.MM.yyyy"))
        self.seans_tarih_label.setText(_translate("seans_saat_label", "Tarihi:"))
        self.seans_tarih_label_2.setText(_translate("seans_saat_label", "Saati:"))
        self.seans_saat_edit.setDisplayFormat(_translate("seans_saat_label", "HH:mm:ss"))
import img_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    seans_saat_label = QtWidgets.QDialog()
    ui = Ui_seans_saat_label()
    ui.setupUi(seans_saat_label)
    seans_saat_label.show()
    sys.exit(app.exec_())
